# Streamlit configuration for Snowflake in-Snowflake (SiS) deployment
# This file should be uploaded alongside the Streamlit app when deploying to Snowflake

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0066CC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[runner]
fastReruns = true
